name: QuestKit
main: io.github.xanderstuff.questkit.QuestKitPlugin
version: "${version}"
api-version: "${apiVersion}"
website: https://github.com/xanderstuff/QuestKit
authors:
  - xanderstuff
  - 0TickPulse
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}
