name: Build
on:
  workflow_call:
    outputs:
      version:
        description: Built version
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
      - name: Gradle Build
        run: ./gradlew build
      - name: Get Version
        id: version
        run: echo ::set-output name=version::"$(./gradlew --console plain --quiet currentVersion -Prelease.quiet)"
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/libs/*.jar
          retention-days: 7
