name: PR
on: pull_request

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
