name: Release
on:
  push:
    tags:
      - 'release-*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Gradle Build
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
      - name: Extract version
        uses: frabert/replace-string-action@master
        id: format-version
        with:
          pattern: 'refs/tags/release-([0-9]+.[0-9]+.[0-9]+)'
          string: ${{ github.ref }}
          replace-with: '$1'
      - name: Release
        uses: docker://antonyurchenko/git-release:v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            build/libs/mc-kotlin-plugin-template-${{ steps.format-version.outputs.replaced }}.jar
            build/libs/mc-kotlin-plugin-template-${{ steps.format-version.outputs.replaced }}-nokt.jar
