name: Release
on:
  push:
    tags:
      - 'release-*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Extract version
        uses: frabert/replace-string-action@v2.0
        id: format-version
        with:
          pattern: 'refs/tags/release-([0-9]+.[0-9]+.[0-9]+)'
          string: ${{ github.ref }}
          replace-with: '$1'
      - name: Release
        uses: docker://antonyurchenko/git-release:v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          TAG_PREFIX_REGEX: "release-"
        with:
          args: |
            build/libs/*.jar
